### ISSUE TITLE
crash when request /api/tasks

### ISSUE THREAD

**Issue by noizbuster** [asmodehn/celeros#18]
I tried to request flower's api /api/tasks

despite to suppose I made bad request, It should be 4xx status, I think

Here is my crash trace

```
ERROR:tornado.application:Uncaught exception GET /api/tasks (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5555', method='GET', uri='/api/tasks', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:5555', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0'})
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/web.py", line 2607, in wrapper
    return method(self, *args, **kwargs)
  File "/opt/groot/bootstrap_stable_ws/src/celeros/deps/flower/flower/api/tasks.py", line 447, in get
    worker=worker, state=state):
  File "/opt/groot/bootstrap_stable_ws/src/celeros/deps/flower/flower/utils/tasks.py", line 21, in iter_tasks
    any_value_search_term = search_terms.get('any', None)
AttributeError: 'NoneType' object has no attribute 'get'
ERROR:tornado.access:500 GET /api/tasks (127.0.0.1) 0.62ms
```

**Comment by asmodehn** [comment]
Please try again. for me I do not have error after this commit.
I basically updated our flower version.
If all is working, please close this issue.

**Comment by asmodehn** [comment]
@noizbuster any news about this ? did you try it ?

**Comment by noizbuster** [comment]
After I update, it works!
