### ISSUE TITLE
concurrent futures dependency missing

### ISSUE THREAD

**Issue by hughie** [asmodehn/celeros#39]
```
A common cause is that the machine cannot ping itself.  Please check
for errors by running:

        ping concert

For more tips, please see

        http://www.ros.org/wiki/ROS/NetworkSetup
^[[0m
^[[31mThe traceback for the exception was written to the log file^[[0m
+ python -tt -m rostful run -h 0.0.0.0 -p 8080 -s flask -c /opt/yujin/amd64/indigo-devel/share/gocart_concert/configs/rostful.cfg -l /home/yujin/.ros/concert/rostful.log '--ros-arg=~connections_list:=/concert/connection_cache/list' '--ros-arg=~connections_diff:=/concert/connection_cache/diff' --ros-arg=__name:=rostful --ros-arg=__log:=/home/yujin/.ros/log/4296bf3e-b7b1-11e6-ae6b-00215cce7859/rostful-12.log
+ python -tt -m celeros worker --beat --config gopher_tasks.beatconfig --hostname beat.concert -S gopher_tasks.scheduler.GopherScheduler -l INFO -f /home/yujin/.ros/log/celeros.log '--ros-arg=~connections_list:=/concert/connection_cache/list' '--ros-arg=~connections_diff:=/concert/connection_cache/diff' --ros-arg=__name:=celeros --ros-arg=__log:=/home/yujin/.ros/log/4296bf3e-b7b1-11e6-ae6b-00215cce7859/celeros-13.log
+ python -tt -m flower --port=5555 --address=0.0.0.0 --conf=/opt/yujin/amd64/indigo-devel/share/celeros/celeros/flowerconfig.py --config=gopher_tasks.beatconfig --logging=INFO --log_file_prefix=/home/yujin/.ros/log/4296bf3e-b7b1-11e6-ae6b-00215cce7859/flower-14.log
+ python -tt -m task_planner run -p 8887 -C gopher_tasks.config_task_planner --ros-arg=__name:=task_planner_server --ros-arg=__log:=/home/yujin/.ros/log/4296bf3e-b7b1-11e6-ae6b-00215cce7859/task_planner_server-15.log
WARNING:root:ZMQ : Protobuf message implementation not found. Using pickle based protocol
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/command.py", line 18, in <module>
    from .app import Flower
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/app.py", line 6, in <module>
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
^[[31m[flower-14] process has died [pid 29519, exit code 1, cmd /opt/yujin/amd64/indigo-devel/lib/celeros/flower --port 5555 --address 0.0.0.0 --conf /opt/yujin/amd64/indigo-devel/share/celeros/celeros/flowerconfig.py --config gopher_tasks.beatconfig --logging INFO __name:=flower __log:=/home/yujin/.ros/log/4296bf3e-b7b1-11e6-ae6b-00215cce7859/flower-14.log].
log file: /home/yujin/.ros/log/4296bf3e-b7b1-11e6-ae6b-00215cce7859/flower-14*.log^[[0m

```

**Comment by asmodehn** [comment]
Solved by adding the dependency into package.xml

**Comment by hughie** [comment]
this is aplied to master branch only. gopher softeare is using gopher-devel branch.
