### ISSUE TITLE
flower is terminated cause dependency module has missing attribute.

### ISSUE THREAD

**Issue by hughie** [asmodehn/celeros#43]
Running on ubuntu 14.04.05
AttributeError: 'module' object has no attribute 'GoogleOAuth2Mixin'

```
INFO:rostful:rostful started with : host 0.0.0.0 port 8080 config /opt/groot/concert_ws/src/gopher_concert/gocart_concert/configs/rostful.cfg logfile /home/yujin/.ros/concert/rostful.log ros_args (u'~connections_list:=/concert/connection_cache/list', u'~connections_diff:=/concert/connection_cache/diff', u'__name:=rostful', u'__log:=/home/yujin/.ros/log/1764e194-cbd7-11e6-83e8-54271efafafc/rostful-12.log')
WARNING:root:Setting up pyros ROS node...
WARNING:root:ZMQ : Protobuf message implementation not found. Using pickle based protocol
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/groot/bootstrap_ws/src/celeros/deps/flower/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/opt/groot/bootstrap_ws/src/celeros/deps/flower/flower/command.py", line 18, in <module>
    from .app import Flower
  File "/opt/groot/bootstrap_ws/src/celeros/deps/flower/flower/app.py", line 16, in <module>
    from .urls import handlers
  File "/opt/groot/bootstrap_ws/src/celeros/deps/flower/flower/urls.py", line 11, in <module>
    from .views import auth
  File "/opt/groot/bootstrap_ws/src/celeros/deps/flower/flower/views/auth.py", line 22, in <module>
    class GoogleAuth2LoginHandler(BaseHandler, tornado.auth.GoogleOAuth2Mixin):
AttributeError: 'module' object has no attribute 'GoogleOAuth2Mixin'
[rostful] Node started as [10980 <= ipc:///tmp/zmp-rostful-q3sqmc/services.pipe]
[WARN] [WallTime: 1482803537.781411] Gateway : uuid's disabled, using possibly non-unique name [GoCart Concert]
[ WARN] Hub : redis-server not found
[ WARN] Hub :     either you can't look up the admin PATH (ok)
[ WARN] Hub :     or it is not installed - hint 'rosdep install rocon_hub'
[INFO] [WallTime: 1482803537.788013] Hub : version 2.8.4
[flower-14] process has died [pid 10723, exit code 1, cmd /opt/groot/bootstrap_ws/src/celeros/scripts/flower --port 5555 --address 0.0.0.0 --conf /opt/groot/bootstrap_ws/src/celeros/celeros/flowerconfig.py --config gopher_tasks.beatconfig --logging INFO __name:=flower __log:=/home/yujin/.ros/log/1764e194-cbd7-11e6-83e8-54271efafafc/flower-14.log].
log file: /home/yujin/.ros/log/1764e194-cbd7-11e6-83e8-54271efafafc/flower-14*.log
INFO root:Starting celery with arguments ['worker', '--beat', '--hostname=beat.yujin-alien', '--scheduler=gopher_tasks.scheduler.GopherScheduler', '--loglevel=INFO', '--logfile=/home/yujin/.ros/log/celeros.log', '--config=gopher_tasks.beatconfig', '--ros-arg=~connections_list:=/concert/connection_cache/list', '--ros-arg=~connections_diff:=/concert/connection_cache/diff', '--ros-arg=__name:=celeros', '--ros-arg=__log:=/home/yujin/.ros/log/1764e194-cbd7-11e6-83e8-54271efafafc/celeros-13.log']
```

**Comment by asmodehn** [comment]
This is because the tornado dependency has the wrong version. Be careful of where tornado is found and what is the version at that location.

I ll keep this issue open for a while in case we hit that problem again.

**Comment by gogopg** [comment]
This is happened again in my machine.
Environment 
* ubuntu 14.04.05
* Virtualbox
* ```ii  python-tornado                                        3.1.1-1ubuntu2```
* No rosbridge-server 

Tried : 
1. install ubuntu
2. ```yujin_anisble podium-ros```

Error :
```
process[rocon/interactions-44]: started with pid [11794]
[ INFO] [1485395533.730181534]: AR tracker reconfigured: ENABLED 10.00 24.30 0.08 0.20
[ INFO] [1485395534.243243331]: CmdVelMux : (re)configured
WARNING:root:ZMQ : Protobuf message implementation not found. Using pickle based protocol

(gst-plugin-scanner:11702): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsteglglessink.so': /usr/lib/x86_64-linux-gnu/libgstegl-1.0.so.0: undefined symbol: eglDestroyImageKHR
[ INFO] [1485395535.763464562]: Subscribing to image topic
[ INFO] [1485395536.089338480]: Reconfigure request : 1.000000 3.000000 0.300000 1.000000 2.000000
WARNING:root:ZMQ : Protobuf message implementation not found. Using pickle based protocol
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/command.py", line 18, in <module>
    from .app import Flower
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/app.py", line 16, in <module>
    from .urls import handlers
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/urls.py", line 11, in <module>
    from .views import auth
  File "/opt/yujin/amd64/indigo-devel/lib/python2.7/dist-packages/flower/views/auth.py", line 22, in <module>
    class GoogleAuth2LoginHandler(BaseHandler, tornado.auth.GoogleOAuth2Mixin):
AttributeError: 'module' object has no attribute 'GoogleOAuth2Mixin'
[ INFO] [1485395536.381059046]: Subscribing to image topic
[flower-40] process has died [pid 11738, exit code 1, cmd /opt/yujin/amd64/indigo-devel/lib/celeros/flower --port 5556 --address 0.0.0.0 --conf /opt/yujin/amd64/indigo-devel/share/celeros/celeros/flowerconfig.py --config gopher_tasks.config_concert --logging INFO __name:=flower __log:=/home/yujin/.ros/log/0be17454-e36a-11e6-abe3-080027930dc5/flower-40.log].
log file: /home/yujin/.ros/log/0be17454-e36a-11e6-abe3-080027930dc5/flower-40*.log
```

**Comment by asmodehn** [comment]
This https://github.com/asmodehn/celeros/blob/gopher-devel/package.xml#L29
needs to be changed to <run_depend>tornado</run_depend>

I did it previously, maybe it was lost in all the
megingr/tagging/branching/releasing problems we had...

--
AlexV
