### ISSUE TITLE
Key error - unknown bootstep

### ISSUE THREAD

**Issue by hughie** [asmodehn/celeros#44]
KeyError: u"unknown bootstep: 'celery.worker.components:Pool'"

```
WARNING:root:Setting up pyros actual client...
[core/dynparam_ar_tracker_short_range_yujin_alien_677_727676070176089351-14] process has finished cleanly
log file: /home/yujin/.ros/log/79333b66-cbee-11e6-a939-54271efafafc/core-dynparam_ar_tracker_short_range_yujin_alien_677_727676070176089351-14*.log
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/groot/bootstrap_ws/src/celeros/celeros/__main__.py", line 150, in <module>
    cli()
  File "/opt/groot/bootstrap_ws/src/rostful/deps/click/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/groot/bootstrap_ws/src/rostful/deps/click/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/groot/bootstrap_ws/src/rostful/deps/click/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/groot/bootstrap_ws/src/rostful/deps/click/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/groot/bootstrap_ws/src/rostful/deps/click/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/groot/bootstrap_ws/src/celeros/celeros/__main__.py", line 144, in worker
    celeros_app.worker_main(argv=argv)
  File "/usr/lib/python2.7/dist-packages/celery/app/base.py", line 176, in worker_main
    app=self).execute_from_commandline(argv)
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 300, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 338, in handle_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 263, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/bin/worker.py", line 203, in run
    hostname=hostname, pool_cls=pool_cls, loglevel=loglevel, **kwargs
  File "/usr/lib/python2.7/dist-packages/celery/worker/__init__.py", line 106, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/lib/python2.7/dist-packages/celery/worker/__init__.py", line 147, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/bootsteps.py", line 214, in apply
    for S in self._finalize_steps(steps):
  File "/usr/lib/python2.7/dist-packages/celery/bootsteps.py", line 257, in _finalize_steps
    raise KeyError('unknown bootstep: %s' % exc)
KeyError: u"unknown bootstep: 'celery.worker.components:Pool'"
[INFO] [WallTime: 1482813586.667727] ConnectionCacheProxy: started inside node /rocon/gateway
[INFO] [WallTime: 1482813586.668123]                     : with list topic at /rocon/connection_cache/list
[INFO] [WallTime: 1482813586.668371]                     : and diff topic at /rocon/connection_cache/diff
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
[core/dynparam_ar_tracker_long_range_yujin_alien_677_2719240590043523409-16] process has finished cleanly
log file: /home/yujin/.ros/log/79333b66-cbee-11e6-a939-54271efafafc/core-dynparam_ar_tracker_long_range_yujin_alien_677_2719240590043523409-16*.log
[celeros-39] process has died [pid 1273, exit code 1, cmd /opt/groot/bootstrap_ws/src/celeros/scripts/celeros --config gopher_tasks.config_concert --hostname yujin-alien --loglevel INFO -f /home/yujin/.ros/log/celeros.log ~connections_list:=/rocon/connection_cache/list ~connections_diff:=/rocon/connection_cache/diff __name:=celeros __log:=/home/yujin/.ros/log/79333b66-cbee-11e6-a939-54271efafafc/celeros-39.log].
log file: /home/yujin/.ros/log/79333b66-cbee-11e6-a939-54271efafafc/celeros-39*.log
```

**Comment by hughie** [comment]
because of : 
```
/usr/bin/python: cannot import name maybe_sanitize_url; 'celeros' is a package and cannot be directly executed
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/groot/bootstrap_ws/src/celeros/deps/flower/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/opt/groot/bootstrap_ws/src/celeros/deps/flower/flower/command.py", line 15, in <module>
    from celery.bin.base import Command
  File "/opt/groot/bootstrap_ws/src/celeros/deps/celery/celery/bin/__init__.py", line 3, in <module>
    from .base import Option
  File "/opt/groot/bootstrap_ws/src/celeros/deps/celery/celery/bin/base.py", line 86, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency
  File "/opt/groot/bootstrap_ws/src/celeros/deps/celery/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/opt/groot/bootstrap_ws/src/celeros/deps/celery/celery/app/__init__.py", line 22, in <module>
    from .base import Celery, AppPickler
  File "/opt/groot/bootstrap_ws/src/celeros/deps/celery/celery/app/base.py", line 43, in <module>
    from .utils import (
  File "/opt/groot/bootstrap_ws/src/celeros/deps/celery/celery/app/utils.py", line 18, in <module>
    from kombu.utils.url import maybe_sanitize_url
ImportError: cannot import name maybe_sanitize_url

```

**Comment by asmodehn** [comment]
This seems to have been triggered because kombu was not set to the right version.

After switching git branches with 'git checkout' it is always needed to 'git submodule update'

I ll keep this issue open for a while in case we hit that problem again...

**Comment by hughie** [comment]
I updated submodule. Are these expected version?
```
yujin@yujin-alien:/opt/groot/bootstrap_ws/src/celeros/deps$ git submodule status
 38a005fffce71c481647175cbde2e3344cd9c2a5 Flask-Celery-Helper (v1.1.0-3-g38a005f)
 2eb26145190bbbb8ea4e31fa5d5ffcc594800804 billiard (v3.3.0.22)
 1996e612745ed55844f7f96baadb9b64b0b7cac4 celery (v3.1.20)
 8b17282434a29a6424c3c2cb855f7e679b1d9985 celerybeatredis (remotes/origin/celeros)
 d21fbca4348bfb76dafcaac359a16272fe96338f flower (v0.8.2-145-gd21fbca)
 5d48da8e43ef66882af01df68dc33e5134a38039 kombu (v3.0.33)
 ad8e232487a1b9e2f17b361cc4f87740df2134f9 redis (2.10.5)
 e718bfde8315ac91e09ff4fc1fa421515afca294 tornado-cors (e718bfd)
```

**Comment by asmodehn** [comment]
The versions seems fine : http://docs.celeryproject.org/en/3.1/changelog.html#version-3-1-20

kombu has maybe_sanitize_url since 4.0.0 : https://github.com/celery/kombu/commit/66419eb780c8392286212c7a73c525277b10c970

So celery 3.1.X should not even try to import this.
Are you sure this is the same error ?

**Comment by hughie** [comment]
No, I'm not sure now. but after that time, I could not see this error.
 
Maybe we can close this issue.
